function x = Es15jacobiana2(x)
    if length(x)~=3; error("Questa funzione richiede tre argomenti"); end
    x = [ ...
        1, -x(3), -x(2); ...
        exp(x(1)+x(2)+x(3)-3), exp(x(1)+x(2)+x(3)-3)-1, exp(x(1)+x(2)+x(3)-3); ...
        1, 1, 2; ...
        ];
    return;
end

